### PR TITLE
Add playbook for installing DBT-7

### PR DESCRIPTION
**Pull request by mw2q**
Add playbooks for installing DBT-7, a TPC Benchmark(TM) DS fair-use implementation.

### CODE REVIEW

**Comment by mw2q** [comment]
@jt-edb Ready for review.  Should be very similar to DBT-3 playbooks.  The variations are mainly around what distro packages to install and what environment variables are used.

**Review by jt-edb — COMMENTED** [review]
Hi Mark - Can you please fix the tests:
```
setup_dbt7-ansible-tester-1  | TASK [edb_devops.edb_postgres.setup_dbt7 : Install packages for DBT-7 Database] ***
setup_dbt7-ansible-tester-1  | fatal: [primary1]: FAILED! => {"changed": false, "msg": "Failure downloading https://github.com/osdldbt/dbt7-packaging/releases/download/v0.4.1/dbt7-0.4.1-1.el8.x86_64.rpm, HTTP Error 404: Not Found"}
```

**Comment by mw2q** [comment]
> Hi Mark - Can you please fix the tests:
> 
> ```
> setup_dbt7-ansible-tester-1  | TASK [edb_devops.edb_postgres.setup_dbt7 : Install packages for DBT-7 Database] ***
> setup_dbt7-ansible-tester-1  | fatal: [primary1]: FAILED! => {"changed": false, "msg": "Failure downloading https://github.com/osdldbt/dbt7-packaging/releases/download/v0.4.1/dbt7-0.4.1-1.el8.x86_64.rpm, HTTP Error 404: Not Found"}
> ```

Fixed! :)

**Review by jt-edb — APPROVED** [review]
LGTM

**Pull request merged**
