### PR TITLE
Added SELinux labeling for custom barman home and ssh directory.

### PR DESCRIPTION
**Pull request by dirkcaumueller**
Dear EDB-team!

As proposed in issue #151 I added to the `setup_barmanserver` role a new variable `barman_default_home` to check against the variable `barman_home` for comparison of custom home directory. In addition, the tasks file `create_user.yml` has new tasks for
* SELinux status check
* Setting SELinux context for custom barman home
* Setting SELinux context for custom barman's ssh directory in the home
* Applying the new SELinux labels to directories/files

Please check the pull request.

Best regards,
Dirk

### CODE REVIEW

**Comment by dirkcaumueller** [comment]
Looks like Ansible moved `firewalld` to `ansible.posix` collection in the newest version. I will have to investigate further. 

```bash
skipping: [primary1]
fatal: [standby1]: FAILED! => {"reason": "couldn't resolve module/action 'firewalld'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/home/centos/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_replication/tasks/setup_replication.yml': line 24, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Open Postgres TCP port {{ pg_port }}\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

skipping: [standby1]
fatal: [primary1]: FAILED! => {"reason": "couldn't resolve module/action 'firewalld'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/home/centos/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/init_dbserver/tasks/init_dbserver.yml': line 28, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Open Postgres TCP port {{ pg_port }}\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

```

**Comment by vibhorkumar123** [comment]
Hi @dirkcaumueller, Thank you for the PR! 
PR is failing on linting. Can you please fix the lint issues?

**Comment by dirkcaumueller** [comment]
Dear @vibhorkumar123!

I added two changes:

1. "firewalld" replaced by "ansible.posix.firewalld" module call for all occurences in the collection. This should help with your PR #154.
2. added "changed_when" attribute to SELinux status check to conform with ansible-lint.

Best regards,
Dirk

**Review by jt-edb — APPROVED** [review]
LGTM. Thank you @dirkcaumueller

**Comment by vibhorkumar123** [comment]
Thank you @dirkcaumueller and @jt-edb !
Merging the changes

**Pull request merged**
