### PR TITLE
setup haproxy

### PR DESCRIPTION
**Pull request by hannahms**
- Updates etcd configuration with new yaml configuration file to allow for access to `etcdctl` without flags.
- Adds HAProxy setup for standalone server or alongside a patroni server.

### CODE REVIEW

**Review by vibhorkumar123 — APPROVED** [review]
LGTM!

**Comment by bonesmoses** [comment]
Was there some particular reason to hard-code `maxconn 100` into each haproxy config line?

**Comment by hannahms** [comment]
I set the global `maxconn` parameter to default to 100, but it can be changed by setting the `haproxy_global_maxconn` variable

**Comment by bonesmoses** [comment]
I don't see that variable used in the "Build haproxy_server_lines" task. It's just injected into the HAProxy config itself. It's being overridden in each individual server line to be hardcoded to "maxconn 100". I guess I could be missing something, but that's how I read that task.

**Pull request merged**
